//
// Autogenerated by Thrift Compiler (0.9.2)
//
// DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
//
var thrift = require('thrift');
var Thrift = thrift.Thrift;
var Q = thrift.Q;


var ttypes = require('./order_types');
//HELPER FUNCTIONS AND STRUCTURES

var RpcZaocanOrderService_getOrderListByToken_args = function(args) {
  this.token = null;
  this.offset = null;
  this.count = null;
  if (args) {
    if (args.token !== undefined) {
      this.token = args.token;
    }
    if (args.offset !== undefined) {
      this.offset = args.offset;
    }
    if (args.count !== undefined) {
      this.count = args.count;
    }
  }
};
RpcZaocanOrderService_getOrderListByToken_args.prototype = {};
RpcZaocanOrderService_getOrderListByToken_args.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
      if (ftype == Thrift.Type.STRING) {
        this.token = input.readString();
      } else {
        input.skip(ftype);
      }
      break;
      case 2:
      if (ftype == Thrift.Type.I32) {
        this.offset = input.readI32();
      } else {
        input.skip(ftype);
      }
      break;
      case 3:
      if (ftype == Thrift.Type.I32) {
        this.count = input.readI32();
      } else {
        input.skip(ftype);
      }
      break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

RpcZaocanOrderService_getOrderListByToken_args.prototype.write = function(output) {
  output.writeStructBegin('RpcZaocanOrderService_getOrderListByToken_args');
  if (this.token !== null && this.token !== undefined) {
    output.writeFieldBegin('token', Thrift.Type.STRING, 1);
    output.writeString(this.token);
    output.writeFieldEnd();
  }
  if (this.offset !== null && this.offset !== undefined) {
    output.writeFieldBegin('offset', Thrift.Type.I32, 2);
    output.writeI32(this.offset);
    output.writeFieldEnd();
  }
  if (this.count !== null && this.count !== undefined) {
    output.writeFieldBegin('count', Thrift.Type.I32, 3);
    output.writeI32(this.count);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

var RpcZaocanOrderService_getOrderListByToken_result = function(args) {
  this.success = null;
  if (args) {
    if (args.success !== undefined) {
      this.success = args.success;
    }
  }
};
RpcZaocanOrderService_getOrderListByToken_result.prototype = {};
RpcZaocanOrderService_getOrderListByToken_result.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 0:
      if (ftype == Thrift.Type.LIST) {
        var _size0 = 0;
        var _rtmp34;
        this.success = [];
        var _etype3 = 0;
        _rtmp34 = input.readListBegin();
        _etype3 = _rtmp34.etype;
        _size0 = _rtmp34.size;
        for (var _i5 = 0; _i5 < _size0; ++_i5)
        {
          var elem6 = null;
          elem6 = new ttypes.OrderDigest();
          elem6.read(input);
          this.success.push(elem6);
        }
        input.readListEnd();
      } else {
        input.skip(ftype);
      }
      break;
      case 0:
        input.skip(ftype);
        break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

RpcZaocanOrderService_getOrderListByToken_result.prototype.write = function(output) {
  output.writeStructBegin('RpcZaocanOrderService_getOrderListByToken_result');
  if (this.success !== null && this.success !== undefined) {
    output.writeFieldBegin('success', Thrift.Type.LIST, 0);
    output.writeListBegin(Thrift.Type.STRUCT, this.success.length);
    for (var iter7 in this.success)
    {
      if (this.success.hasOwnProperty(iter7))
      {
        iter7 = this.success[iter7];
        iter7.write(output);
      }
    }
    output.writeListEnd();
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

var RpcZaocanOrderService_getOrderCountByToken_args = function(args) {
  this.token = null;
  if (args) {
    if (args.token !== undefined) {
      this.token = args.token;
    }
  }
};
RpcZaocanOrderService_getOrderCountByToken_args.prototype = {};
RpcZaocanOrderService_getOrderCountByToken_args.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
      if (ftype == Thrift.Type.STRING) {
        this.token = input.readString();
      } else {
        input.skip(ftype);
      }
      break;
      case 0:
        input.skip(ftype);
        break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

RpcZaocanOrderService_getOrderCountByToken_args.prototype.write = function(output) {
  output.writeStructBegin('RpcZaocanOrderService_getOrderCountByToken_args');
  if (this.token !== null && this.token !== undefined) {
    output.writeFieldBegin('token', Thrift.Type.STRING, 1);
    output.writeString(this.token);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

var RpcZaocanOrderService_getOrderCountByToken_result = function(args) {
  this.success = null;
  if (args) {
    if (args.success !== undefined) {
      this.success = args.success;
    }
  }
};
RpcZaocanOrderService_getOrderCountByToken_result.prototype = {};
RpcZaocanOrderService_getOrderCountByToken_result.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 0:
      if (ftype == Thrift.Type.I32) {
        this.success = input.readI32();
      } else {
        input.skip(ftype);
      }
      break;
      case 0:
        input.skip(ftype);
        break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

RpcZaocanOrderService_getOrderCountByToken_result.prototype.write = function(output) {
  output.writeStructBegin('RpcZaocanOrderService_getOrderCountByToken_result');
  if (this.success !== null && this.success !== undefined) {
    output.writeFieldBegin('success', Thrift.Type.I32, 0);
    output.writeI32(this.success);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

var RpcZaocanOrderServiceClient = exports.Client = function(output, pClass) {
    this.output = output;
    this.pClass = pClass;
    this._seqid = 0;
    this._reqs = {};
};
RpcZaocanOrderServiceClient.prototype = {};
RpcZaocanOrderServiceClient.prototype.seqid = function() { return this._seqid; }
RpcZaocanOrderServiceClient.prototype.new_seqid = function() { return this._seqid += 1; }
RpcZaocanOrderServiceClient.prototype.getOrderListByToken = function(token, offset, count, callback) {
  this._seqid = this.new_seqid();
  if (callback === undefined) {
    var _defer = Q.defer();
    this._reqs[this.seqid()] = function(error, result) {
      if (error) {
        _defer.reject(error);
      } else {
        _defer.resolve(result);
      }
    };
    this.send_getOrderListByToken(token, offset, count);
    return _defer.promise;
  } else {
    this._reqs[this.seqid()] = callback;
    this.send_getOrderListByToken(token, offset, count);
  }
};

RpcZaocanOrderServiceClient.prototype.send_getOrderListByToken = function(token, offset, count) {
  var output = new this.pClass(this.output);
  output.writeMessageBegin('getOrderListByToken', Thrift.MessageType.CALL, this.seqid());
  var args = new RpcZaocanOrderService_getOrderListByToken_args();
  args.token = token;
  args.offset = offset;
  args.count = count;
  args.write(output);
  output.writeMessageEnd();
  return this.output.flush();
};

RpcZaocanOrderServiceClient.prototype.recv_getOrderListByToken = function(input,mtype,rseqid) {
  var callback = this._reqs[rseqid] || function() {};
  delete this._reqs[rseqid];
  if (mtype == Thrift.MessageType.EXCEPTION) {
    var x = new Thrift.TApplicationException();
    x.read(input);
    input.readMessageEnd();
    return callback(x);
  }
  var result = new RpcZaocanOrderService_getOrderListByToken_result();
  result.read(input);
  input.readMessageEnd();

  if (null !== result.success) {
    return callback(null, result.success);
  }
  return callback('getOrderListByToken failed: unknown result');
};
RpcZaocanOrderServiceClient.prototype.getOrderCountByToken = function(token, callback) {
  this._seqid = this.new_seqid();
  if (callback === undefined) {
    var _defer = Q.defer();
    this._reqs[this.seqid()] = function(error, result) {
      if (error) {
        _defer.reject(error);
      } else {
        _defer.resolve(result);
      }
    };
    this.send_getOrderCountByToken(token);
    return _defer.promise;
  } else {
    this._reqs[this.seqid()] = callback;
    this.send_getOrderCountByToken(token);
  }
};

RpcZaocanOrderServiceClient.prototype.send_getOrderCountByToken = function(token) {
  var output = new this.pClass(this.output);
  output.writeMessageBegin('getOrderCountByToken', Thrift.MessageType.CALL, this.seqid());
  var args = new RpcZaocanOrderService_getOrderCountByToken_args();
  args.token = token;
  args.write(output);
  output.writeMessageEnd();
  return this.output.flush();
};

RpcZaocanOrderServiceClient.prototype.recv_getOrderCountByToken = function(input,mtype,rseqid) {
  var callback = this._reqs[rseqid] || function() {};
  delete this._reqs[rseqid];
  if (mtype == Thrift.MessageType.EXCEPTION) {
    var x = new Thrift.TApplicationException();
    x.read(input);
    input.readMessageEnd();
    return callback(x);
  }
  var result = new RpcZaocanOrderService_getOrderCountByToken_result();
  result.read(input);
  input.readMessageEnd();

  if (null !== result.success) {
    return callback(null, result.success);
  }
  return callback('getOrderCountByToken failed: unknown result');
};
var RpcZaocanOrderServiceProcessor = exports.Processor = function(handler) {
  this._handler = handler
}
RpcZaocanOrderServiceProcessor.prototype.process = function(input, output) {
  var r = input.readMessageBegin();
  if (this['process_' + r.fname]) {
    return this['process_' + r.fname].call(this, r.rseqid, input, output);
  } else {
    input.skip(Thrift.Type.STRUCT);
    input.readMessageEnd();
    var x = new Thrift.TApplicationException(Thrift.TApplicationExceptionType.UNKNOWN_METHOD, 'Unknown function ' + r.fname);
    output.writeMessageBegin(r.fname, Thrift.MessageType.EXCEPTION, r.rseqid);
    x.write(output);
    output.writeMessageEnd();
    output.flush();
  }
}

RpcZaocanOrderServiceProcessor.prototype.process_getOrderListByToken = function(seqid, input, output) {
  var args = new RpcZaocanOrderService_getOrderListByToken_args();
  args.read(input);
  input.readMessageEnd();
  if (this._handler.getOrderListByToken.length === 3) {
    Q.fcall(this._handler.getOrderListByToken, args.token, args.offset, args.count)
      .then(function(result) {
        var result = new RpcZaocanOrderService_getOrderListByToken_result({success: result});
        output.writeMessageBegin("getOrderListByToken", Thrift.MessageType.REPLY, seqid);
        result.write(output);
        output.writeMessageEnd();
        output.flush();
      }, function (err) {
        var result = new RpcZaocanOrderService_getOrderListByToken_result(err);
        output.writeMessageBegin("getOrderListByToken", Thrift.MessageType.REPLY, seqid);
        result.write(output);
        output.writeMessageEnd();
        output.flush();
      });
  } else {
    this._handler.getOrderListByToken(args.token, args.offset, args.count,  function (err, result) {
      var result = new RpcZaocanOrderService_getOrderListByToken_result((err != null ? err : {success: result}));
      output.writeMessageBegin("getOrderListByToken", Thrift.MessageType.REPLY, seqid);
      result.write(output);
      output.writeMessageEnd();
      output.flush();
    });
  }
}

RpcZaocanOrderServiceProcessor.prototype.process_getOrderCountByToken = function(seqid, input, output) {
  var args = new RpcZaocanOrderService_getOrderCountByToken_args();
  args.read(input);
  input.readMessageEnd();
  if (this._handler.getOrderCountByToken.length === 1) {
    Q.fcall(this._handler.getOrderCountByToken, args.token)
      .then(function(result) {
        var result = new RpcZaocanOrderService_getOrderCountByToken_result({success: result});
        output.writeMessageBegin("getOrderCountByToken", Thrift.MessageType.REPLY, seqid);
        result.write(output);
        output.writeMessageEnd();
        output.flush();
      }, function (err) {
        var result = new RpcZaocanOrderService_getOrderCountByToken_result(err);
        output.writeMessageBegin("getOrderCountByToken", Thrift.MessageType.REPLY, seqid);
        result.write(output);
        output.writeMessageEnd();
        output.flush();
      });
  } else {
    this._handler.getOrderCountByToken(args.token,  function (err, result) {
      var result = new RpcZaocanOrderService_getOrderCountByToken_result((err != null ? err : {success: result}));
      output.writeMessageBegin("getOrderCountByToken", Thrift.MessageType.REPLY, seqid);
      result.write(output);
      output.writeMessageEnd();
      output.flush();
    });
  }
}

